import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function MovieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site Legal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {info.title}
        </h1>

        <p>Nota: {info.vote_average}</p>

        <p>{info.overview}</p>

        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width='400' />

        <Link href="/busca"><button className={styles.myButton}>Ir para a Busca</button></Link>
        <Link href="/"><button className={styles.myButton}>Ir para a Home</button></Link>  
        
      </main>
    </div>
  )
}

// Com essa exportação a página vira uma página estatica 
// (context) consegue pegar o valor do arquivo
export async function getServerSideProps(context) {

  // Vai pegar as informações do filme
  // Vai fazer requisição baseado no id que esta no arquivo JS
  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
  const json = await res.json();

//   console.log("JSON", json)

  // Fica resposavel por enviar os props
  return {
    props: {
      info: json.info
    }
  }
}