import Head from 'next/head'
import Link from 'next/link'
import {useState} from 'react'
import styles from '../styles/Home.module.css'

export default function Busca({list}) {

  // Vai pegar e guarar informação da pesquisa
  const [searchText, setSearchText] = useState(' ')

  // Salvar o resultado da procura 
  const [movieList, setMovieList] = useState([])

  // Faz a requisição com o que foi escrito na busca
  const handleSearch = async () => {
    const result = await fetch(`http://localhost:3000/api/search?q=${searchText}`)
    const json = await result.json()
    setMovieList(json.list)
    // console.log(json)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Site Legal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Busca
        </h1>

        <input 
        type='text' 
        value={searchText} 
        onChange={e=>setSearchText(e.target.value)}/>
        {/* Termo de Busca: {searchText} */}
        <button onClick={handleSearch}>Buscar</button>

        <hr/>

        <ul>
            {movieList.map(item=>(
                <li>
                <a href={`/movie/${item.id}`}>
                  <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width='150'/><br/>
                  {item.title}
                </a>
              </li>
            ))}
        </ul>

        <Link href="/"><button className={styles.myButton}>Ir para a Home</button></Link>
        <Link href="/sobre"><button className={styles.myButton}>Ir para o Sobre</button></Link>
      </main>
    </div>
  )
}

// CLIENTE SIDE READERING NÃO PRECISA DA EXPORTAÇÃO ABAIXO!!!!!!!!!!!!!!!!!!!!!!!!!

// Com essa exportação a página vira Server Side Readering 
// export async function getServerSideProps() {

//   const res = await fetch('http://localhost:3000/api/trending');
//   const json = await res.json();

//   // Fica resposavel por enviar os props
//   return {
//     props: {
//       list: json.list
//     }
//   }
// }