import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Site Legal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre o Sistema
        </h1>

        <p>O sistema foi feito na Framework Next.js</p>

        <hr/>

        Autor: {author}

        <br/>
        <br/> 

        <Link href="/busca"><button className={styles.myButton}>Ir para a busca</button></Link>
        <Link className="myButton" href="/"><button className={styles.myButton}>Ir para a Home</button></Link>
      </main>
    </div>
  )
}

// Com essa exportação a página vira Server Side Readering 
export async function getStaticProps() {
  // Fica resposavel por enviar os props
  return {
    props: {
      author: 'Ygor'
    }
  }
}